# Generated by Django 5.1.4 on 2025-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psalm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва псалму')),
                ('text', models.TextField(error_messages={'blank': 'Це поле обов"язкове для заповнення.'}, verbose_name='Текст псалму')),
            ],
            options={
                'verbose_name': 'Псалми',
            },
        ),
    ]
