# Generated by Django 5.1.4 on 2025-02-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psalm',
            options={'verbose_name': 'Псалом', 'verbose_name_plural': 'Псалми'},
        ),
    ]
