# Generated by Django 5.1.4 on 2025-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва молитви')),
                ('text', models.TextField(error_messages={'blank': 'Це поле обов"язкове для заповнення.'}, verbose_name='Текст молитви')),
            ],
            options={
                'verbose_name': 'Молитва',
                'verbose_name_plural': 'Молитви',
            },
        ),
    ]
